version: '2.1'
services:

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "test:1:1,ordering:1:1,restaurant:1:1,eta:1:1,delivery:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    healthcheck:
        test: "kafka-topics.sh --zookeeper zk:2181 --list 2>&1 | grep \"delivery\""

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  api-gateway:
    image: uberoolab/team-d-apigateway
    depends_on:
      kafka:
        condition: service_healthy
    ports:
     - "8080:5000"

  menu:
    image: uberoolab/team-d-menu-service
    depends_on:
     menu-database:
      condition: service_healthy
     kafka:
       condition: service_healthy
    ports:
     - "4000:5000"

  menu-database:
    image: uberoolab/team-d-menu-database
    ports:
     - "4010:3306"
    healthcheck:
      test: "mysqladmin ping --silent"


  order:
    image: uberoolab/team-d-ordering-service
    depends_on:
      kafka:
        condition: service_healthy
      ordering-database:
        condition: service_healthy
    ports:
     - "4001:5000"

  ordering-database:
    image: uberoolab/team-d-ordering-database
    ports:
     - "4011:3306"
    healthcheck:
      test: "mysqladmin ping --silent"


  eta:
    image: uberoolab/team-d-eta-computer-service
    ports:
     - "4002:5000"


#  chinese-restaurant:
#    image: uberoolab/team-d-chinese-restaurant-service
#    environment:
#      - DATABASE_CHINESE_RESTAURANT=chinese-restaurant-database:3306
#    depends_on:
#      - chinese-restaurant-database
#    ports:
#     - "4003:8080"

#  chinese-restaurant-database:
#    image: uberoolab/team-d-chinese-restaurant-database
#    ports:
#     - "4013:3306"


  delivery:
    image: uberoolab/team-d-delivery-service
    environment:
      - DATABASE_DELIVERY=delivery-database:3306
    depends_on:
     delivery-database:
      condition: service_healthy
     kafka:
      condition: service_healthy
    ports:
     - "4004:8080"

  delivery-database:
    image: uberoolab/team-d-delivery-database
    ports:
     - "4014:3306"
    healthcheck:
      test: "mysqladmin ping --silent"
 
