version: '3'
services:
  menu:
    image: uberoolab/team-d-menu-service
    ports:
     - "4000:5000"
  order:
    image: uberoolab/team-d-ordering-service
    ports:
     - "4001:5000"
  chinese-restaurant:
    image: uberoolab/team-d-chinese-restaurant-service:1.0 
    ports:
     - "4003:8080"
  delivery:
    image: uberoolab/team-d-delivery-service:1.0 
    ports:
     - "4004:8080"