version: '3'
services:
  chinese-restaurant:
    image: uberoolab/team-d-chinese-restaurant-service:1.0 
    ports:
     - "4003:8080"
  delivery:
    image: uberoolab/team-d-delivery-service:1.0 
    ports:
     - "4004:8080"