---
swagger: "2.0"
info:
  description: "This documentation describes Uberoo Api Gateway made by the team C\
    \ during the SOA lab - SI5 2018-2019 at Polytech'Nice Sophia Antipolis\n"
  version: "1.0.0"
  title: "Uberoo Api Gateway"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "restaurants"
  description: "Everything about restaurants"
schemes:
- "http"
paths:
  /list_categories:
    get:
      tags:
      - "restaurants"
      summary: "Retrieve response after a categories list request"
      description: "Returns a list of available categories"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the previous categories list request"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
        404:
          description: "Request id not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    post:
      tags:
      - "restaurants"
      summary: "Request the list of available categories"
      description: "Multiple status values can be provided with comma separated strings"
      produces:
      - "application/json"
      parameters: []
      responses:
        202:
          description: "successful operation returning the callback url to get the\
            \ result"
          schema:
            $ref: "#/definitions/CallbackUrlListCategories"
        400:
          description: "Invalid status value"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /list_meals_by_category:
    get:
      tags:
      - "restaurants"
      summary: "Retrieve response after a meals by category list request"
      description: "Returns a list of meals corresponding to category requested"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the previous categories list request"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Meal"
        404:
          description: "Request id not found"
      security:
      - api_key: []
    post:
      tags:
      - "restaurants"
      summary: "Request the list of meals corresponding to a category"
      description: "Hello"
      produces:
      - "application/json"
      parameters: []
      responses:
        202:
          description: "successful operation returning the callback url to get the\
            \ result"
          schema:
            $ref: "#/definitions/CallbackUrlListMealsByCategory"
        400:
          description: "Invalid status value"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  CallbackUrlListCategories:
    type: "object"
    properties:
      callbackUrl:
        type: "string"
        format: "uri"
        example: "http://127.0.0.1:5000/list_categories?id=309534062390007280678553008932882969813"
    example:
      callbackUrl: "http://127.0.0.1:5000/list_categories?id=309534062390007280678553008932882969813"
  CallbackUrlListMealsByCategory:
    type: "object"
    properties:
      callbackUrl:
        type: "string"
        format: "uri"
        example: "http://127.0.0.1:5000/list_meals_by_category?id=189983883581989648481499453509713428387"
    example:
      callbackUrl: "http://127.0.0.1:5000/list_meals_by_category?id=189983883581989648481499453509713428387"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 12
      name:
        type: "string"
        example: "Japonais"
      region:
        type: "string"
        example: "Asie"
    example:
      name: "Japonais"
      id: 12
      region: "Asie"
  Meal:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 64
      category:
        $ref: "#/definitions/Category"
      restaurant:
        $ref: "#/definitions/Restaurant"
      name:
        type: "string"
        example: "Sushis saumon"
      price:
        type: "integer"
        format: "float"
        example: "12.42"
      is_menu:
        type: "boolean"
        example: false
      image:
        type: "string"
    example:
      image: "image"
      price: "12.42"
      restaurant:
        name: "Dragon d'Or"
        id: 11
      name: "Sushis saumon"
      id: 64
      category:
        name: "Japonais"
        id: 12
        region: "Asie"
      is_menu: false
  Restaurant:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 11
      name:
        type: "string"
        example: "Dragon d'Or"
    example:
      name: "Dragon d'Or"
      id: 11
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
