version: '3'
services:

  api-gateway:
    image: uberoolab/team-d-apigateway
    depends_on:
     - kafka
    ports:
     - "8080:5000"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "test:1:1,ordering:1:1,restaurant:1:1,eta:1:1,delivery:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  menu:
    image: uberoolab/team-d-menu-service
    depends_on:
     - menu-database
     - kafka
    ports:
     - "4000:5000"

  menu-database:
    image: uberoolab/team-d-menu-database
    ports:
     - "4010:3306"
